sudo: required

language: java
jdk:
  - oraclejdk8

git:
  depth: false

addons:
  sonarcloud:
    organization: "coffeenet"
    token:
      secure: "YQvxJPXshF9NJDk3n57MTB8Q4qIZS4LgcuntR9aBrnOjbZiSYx5a3Qim8Ux8iHCOkCWOQv7hXAUEnKXdp+4z1VMYrjoVsfflHXgw5At8ayUVUEtsdyiP3IgFm6GKDdgFpUszZcgs2XJQp3GVUaLY+PzFkzd7mtswRqCqkU4AkYBD5IFoNH+gLvrmh8V2T7kGsgT0ljm2/Rjbq4vJ6hEcncOIkcIgtSShDcIo5Aoyksfen98s2A1omuqqFwYKldeN9hHlGlMLB7HV5hjeI0BP1xbnen64k3qDn7EyeEDBpTA/iB2VEhVvPaOwJZ/Zskg5sydR775h+xxpuVI89Z3VCpN+rHAiohWqRjThejh/pv/C3XZLyhnIAVwFLFXtAdbO7pcuxtY8+BQRfb2dRHeiM/C+hCTRpDW0t4rkvZBHKXbJf0ai8+nkT1pL0r9B+xxhP1ENBq3I3LD0Zyt7uIVYgi/LF5lK9KjUr5mDltW6SxTmlsP5nFoad6g3R6vylDp4YFJJhgKKEBIxpTnCYeXdIkUCW4MBVD73ZrVUXlRNw94ntJLn6kJoRcud9OEuNpfWW4vk0GLFdPsoX4cdE/TSfXpvlXv7ZnQc25HEmuGzWsDPLmYCx00m9I6rmsFUyUx/A3AegRC9E/DrO7fap0ynLjOxXd+G7t8bxGtpBwoy7GE="

before_install:
  - sudo apt-get install -y markdown

script: ./mvnw clean org.jacoco:jacoco-maven-plugin:prepare-agent test sonar:sonar

before_deploy:
  - export RELEASE_NOTES=$(awk -v start=1 '/^#{2}[[:space:]].*$/{n++;next};n==start;n==start+1{exit}' CHANGELOG.md | markdown | awk '{printf "%s",$0} END {print ""}')

deploy:
  - provider: releases
    api_key:
      secure: F5nXVfVGCZEogpA1m0369Mnsg91pLaPPTuGgwUJy8sozfYkXdrpIuNZM7NJ46fYRo3GCHppyGohpd8chg5djkGGGbWap4ApoHDT15ja1kapaEspb3roDF8wy2ILB4Qh1quE6DHcSyBtb/1Gizwt2blHS7wZAdZUzlghMdfjml22PaecptMyKppw1W+gUs7kfA/ypyLxKlRowVyyDlFTeiGAccdWsyCfUmnNQDPu3Bi9ztpeCohzjcH9SY1PkyGdSe+a93I9YqqJBDRk5AHHCb4mI1c3DPwwm2UEWqZqQwYI24P/RnqvD/mMkUELIGyptrrpPL0ToviPnE1+VkcWqME+Xs8fbVesh3oQMed06FFkvLZCTeZPtZrBepEfu/j5vNtLiMxO++gphY6fxKnWujeablEJLCEkgvt9lYi6jTS6FAMJyjPfSqMwRN44tyBwPb1cJOcg2sVINrz2ZrXoFVCmkfbbSdygubIO/uy6zX7jHBCX8NtX4fpNdQQp9SVhiinEgVUIfz8WRNpGRQSZEQbvg50K06kgzv1LyyQo+vOfnFG34V9tlR/1BVziSyXjNEBfyY9tREqhRDeTvJa5mLDnOl88EYPimkqRkgA2dq0cJfqLzdEKQf5Kxo5ETsjcwbAacUlY92oPdg/q1LwQW+ZwC6KlinPqlpwIKrEiHV5M=
    body: "${RELEASE_NOTES}"
    skip_cleanup: true
    on:
      tags: true
      repo: coffeenet/coffeenet-frontpage-plugin-api

  - provider: script
    script: openssl aes-256-cbc -K $encrypted_592f92e30877_key -iv $encrypted_592f92e30877_iv -in coffeenet.pgp.enc -out coffeenet.pgp -d &&
      gpg --fast-import coffeenet.pgp &&
      ./mvnw deploy -DskipTests --settings ${TRAVIS_BUILD_DIR}/.travis.settings.xml -Prelease
    skip_cleanup: true
    on:
      tags: true
      repo: coffeenet/coffeenet-frontpage-plugin-api

env:
  global:
    - secure: BlLLdFDfI21omluHlH71Ygb9k+gY91DsxkUU5CbYB98yT9rI1g7oO003Sqrvks1zfh1D50e0zQkkh+CUjguEt7Je3wYfoL9qmk1QpWa1a6vv5Ob7+uEIe8mm2RIplotoUIqMULLpz+lbQhr2SEja5rlTzOxQJUYJW4G6vtrBqq/IAc5IkihFq9yFbltSqYf518FtwvfVc3PwXj72ajZA14MlRtMO2nTErjEwbF6qAL9NtDaI11jlSGyFUP+Jl1qghK4Vyze+XSCviu7GXFT9/k83Es47sAomhTquatejj24RGE42gBkPz8PQ8nvX7+v8m/Hq/IgNVKfhQS/yUtLrB+uG3Q8m9RnO9jrFtyV1rIDj338ssO0puw2OOyc4tuyKHJIVnC0f0cfEBsA5/tNFlwxYDmuk8vHYM6gWAp7wHqyweN0/aMJEdkZKRdtVjDZhM6r8jtJ5J+6X9PcozDk+GGLRAIFfElx/RkOYg6Jsa4zNeNR2hPDjirPoiJEMShbr7hcokUA5CqVsD1QUqxzLcpqPJnOXw/JzhIFksR2OXzZX7bKOUyNpc65Qy9jfp8LC1xIBFQmZnEVny57u1wJKaPPDAoWfn5z/6oatE91q8mty+S/vuoeDc719J/72iaqZfQ6rQTwtJpYNq+4IknoudbAuSlZiJ/e0VkxSWsA0ECU=
    - secure: QC+C8dCNmGXrillUY4cjXkAZ4ALco+qLsafdb6YxqF3nQG1k5UE7jjXvad28iVpJIn1CJGDO34glstQBVGj6mLziykmCimSdOE3BxQ/BLYMBi/BmObnSLlIYNwyAzZ7ShgK12QkFKhpdn8oSTeW/8H6FALcrorqRAg/pV64wAd7dxYMHIyqZXd29MjIC9oavhPNZ44IaSvTSarmCH6I8w3cTEuCoVGNMrt3niR6d48i0UhmwBK19FBEnUOg8LL2fmKA5dp+sGWTBJFFXJXqqM9Ot0L517o5XsqGh0b50ohgvCereIZ57feu/isImCBir3R5yUXtGHr+B0UVBTF3bf5bN/oPvKPjWJrcNpUtoVPRaKrRKstS/uNhis396JNsNuYGCsp8fwp+E9xAxXLRwqlCjbyOyIqIW+rvsXjBMjQouWFQvEagBHqRyjEJjVTTRc63BrebWuF2wsst+cuK8CN12394Uj6tN7wC1ADLEXXrpfGuSDQli0PfAE9TfxurcOisA4ytzLB/FDFyvxX7u7rev2M1Anr5ufCLYsMi6XGWQHbRYmrBM6QN2qkmas0AzQ7KEOg1lcrV2hTg31Dtf/GsOWOV/iMUPvptnb7s1mI7qGV0woPJx26ygtxykCK6eWifPyKRZeCHFJdfx3u1yszIdc2Yia4l+GZ9RGnu02Q8=
    - secure: 2g2jLJKSPolnb/dVhDp2+LvKKLIQrL9pucr4BpnubNU0pCFzG2irWv/6xFTll+DLBjK+4l3GbLU7+p+v6moAle5nIpjZAeTSJ3I3bWiIhTI7kKwGYy/Cgf9sKnaSumA4DShtje/br9i9aTTgeQsbyBjAuKz4IPDPHBmF2/NIFbLfkOViwGQvAhtIDKZ99XxAxHleehmdc4TqNywQBJ+Hrwuj1aG1jXp56eQfJ/AiMNpHpfIglxTumi8RPJhPt92LqDe/56WGBAYZ7UP+XYwKX1iQyCo02Q0fscT5zQQlM2yGNjet0xk5lqavMl1vcAR6qWwCP6pOu8IVxNCrPL6msrQZFSQoABMZIloDnIwVGwI5F8V74TLLr5M8ya6UXVujkpa+r0R5paYcLSJqPYc7eV0n2hYaZ3cWWnk6Bg6jpojyPVt4/E1PeYYoLCqlGRXeYqc4XXz620w6MDh/gYu2B7auJhjU2Kx+S79FugVvQXmXpsb6vb+Xy8UvSAhpg4RjKBnGz1Uc5hjUY8IWucrYHF0tEN/E7IGw5G6ZHRl0ndJqoiM5Fo8zs4V2oOsqJIqV0CI+WFtKuKp8B7pvbC6EpWauAZWI33J9ODXTI8JGqmkpme7Zp6Q+CnbSVM+R92WOUpnRT3yCDMaXIZkCJacvafn/azFsyHzRUCn0Fx8hppI=

cache:
  directories:
    - $HOME/.m2
