language: java

script: ./mvnw test

jdk:
  - oraclejdk8

before_deploy:
  - mvn -DskipTests package
  - export JAR_FILE=$(ls target/frontpage-plugin-api*.jar)
  - echo "deploying ${JAR_FILE} to GitHub releases"

deploy:
  - provider: releases
    api_key:
      secure: F5nXVfVGCZEogpA1m0369Mnsg91pLaPPTuGgwUJy8sozfYkXdrpIuNZM7NJ46fYRo3GCHppyGohpd8chg5djkGGGbWap4ApoHDT15ja1kapaEspb3roDF8wy2ILB4Qh1quE6DHcSyBtb/1Gizwt2blHS7wZAdZUzlghMdfjml22PaecptMyKppw1W+gUs7kfA/ypyLxKlRowVyyDlFTeiGAccdWsyCfUmnNQDPu3Bi9ztpeCohzjcH9SY1PkyGdSe+a93I9YqqJBDRk5AHHCb4mI1c3DPwwm2UEWqZqQwYI24P/RnqvD/mMkUELIGyptrrpPL0ToviPnE1+VkcWqME+Xs8fbVesh3oQMed06FFkvLZCTeZPtZrBepEfu/j5vNtLiMxO++gphY6fxKnWujeablEJLCEkgvt9lYi6jTS6FAMJyjPfSqMwRN44tyBwPb1cJOcg2sVINrz2ZrXoFVCmkfbbSdygubIO/uy6zX7jHBCX8NtX4fpNdQQp9SVhiinEgVUIfz8WRNpGRQSZEQbvg50K06kgzv1LyyQo+vOfnFG34V9tlR/1BVziSyXjNEBfyY9tREqhRDeTvJa5mLDnOl88EYPimkqRkgA2dq0cJfqLzdEKQf5Kxo5ETsjcwbAacUlY92oPdg/q1LwQW+ZwC6KlinPqlpwIKrEiHV5M=
    file: "${JAR_FILE}"
    skip_cleanup: true
    on:
      tags: true
      repo: coffeenet/coffeenet-frontpage-plugin-api
  - provider: script
    script: echo "<settings><servers><server><id>releases.public.nexus.synyx.de</id><username>$NEXUS_USERNAME</username><password>$NEXUS_PASS</password></server></servers></settings>" > ~/settings.xml; mvn deploy --settings ~/settings.xml -DskipTests
    skip_cleanup: true
    on:
      tags: true
      repo: coffeenet/coffeenet-frontpage-plugin-api

env:
  global:
  - secure: "AtKBuN3azg6xv2U4Nj2ZzuIWNxLvHdjGhsgJzVNs/y31lcojZ+xoIhHfXo9TYG5zy63hRBnNvKMgfV+vW+HTgh6yC46x2ix5yQKR0XADcLB7OIswBdAaZtfdrL4jX+DtNrNh3GAjsn65AcY26tLSm7HyEU/lsj6W5aDY1E9GR8u8vDrm251jXE0Z2gIgR5vT42hCp4ARmhuxayKJb5K6zERlfcSnZ2CPtjHSPQPlyhluSfzTwEW7qxFxWslulN9Esdq0D2GxrxUEHkAjvBoew2kWGFb6hi/Ua9yHpmZQHp6fI0qA4bI9EBEjXGvnOsKFqHnjYMjKkdkNuJA6yq+4hpNrjsE8iwtLkhEClB2TMVbFAsrkMtnhIq1/+vUrNetQHCbs4JdO/PLhchHPupO9QMqMLBpLw1Iltm5AMThHvmyRsljxDxCN+BxxJOtyWXmH6jw43Ur1n6GW3cQfDGgfi9Q/idRVjDeqj02yV4m/F9IHjn04RrSQn3sSA2+T0UhgF3scCcAbKV/yAwh8mZeFk3coYU99ANQ4si6Au7eMgvxQomdZ8uKhSg/Lwkr7KX0rXj08xDo6bhmcZ0Xb8i0RcpqiDAstXLW4Z3rwUr69NmhSH2DF8Hepcg7wK4tKWxm0z7QfSQIi5G/tngTj8ch/dXqD8ZOh3iS5BFGIodv0J/U="
  - secure: "AC/kl99y4fdE+ps6kNo4yujDKOVMqDETUcmTv0WkGVWEbGUryl8HMFLyz8o7HtOaU8M3Dif5NgB8NC3QfSh0OFtUjuEn0RIOrnQ3pqMNWxyJMgkagB2dbKpEJaflba5CGMiNdQTTpqx0zAeugO5JK6E0NyhLwwFJkDM8AN5gHDiRRWshDJJ/72qM35p5nm4f5CpuQy5tawoJVkXX5EB1Yt120rpcWZxeQOsppuhKP1GyrRdd0jRRihzThij+7boBhiMtNkG7Eoj3oPrbqBJAzUhq1yr+XZp3HNLSPesP3h9UE55TtUFU9W+MrI5yHD8R85oXSVySxyZvvg5cQJ3h4mlFRERrYMDR9PUJnyTfQXuKqppmACoRKA3QgzkxkK+lM5nKFuIjEUcqANEwcST2tfMROmjjK+K0WyvEeQSlHqssBT5gwL1BZLBYyh6yG7i4WAJwBP+6zIlL5UaXr3L3xQz1s5ffJanr6Ojxf09+QV+ju4/0ovUozfuA7VcKrMVS0VL8AzAkpFSkVPfURLc5+ug+hNn2xY6TOZBKQh3Gx5o5y4kkvCpvYDtO7OEsruf4o3tnSstR6qJxsE367tbNhXH0V0OG9bDEEd1cFrZ3we8frIbqM3G3ppBHWKT6NOsmXMOHaEjGtG4PnYBAPn/UqVfWiPCSUfcACNTjFI+IzBg="

notifications:
  irc:
    channels:
      - "irc.synyx.de#CoffeeNet"
    on_success: change # default: always
    on_failure: always # default: always
    use_notice: true
    skip_join: true

cache:
  directories:
    - $HOME/.m2